<?php
/**
 * Created by PhpStorm.
 * User: prook
 * Date: 21.06.2019
 * Time: 13:50
 */

namespace backend\components;

use yii\db\ActiveRecord;
use app\models\Sef;

class MyActiveRecordSef extends MyActiveRecord
{
    protected $_sef;
    protected $_sef_start = '';

    public function getSef()
    {
        $sef_data = Sef::find()
            ->where(['link' => $this->_sef_start . $this->id])
            ->one();
        $this->_sef = $sef_data->link_sef;
        return $this->_sef;
    }
    public function setSef($value)
    {
        $this->_sef = $value;
    }

    /**
     * @inheritdoc
     */
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);

        $class = $this->_desc_class;

        if (empty($this->_sef)) {
            $this->getSef();
        }

        if (!$insert) {
            static::getDb()
                ->createCommand()
                ->delete('sef', ['link' => $this->_sef_start . $this->id])
                ->execute();
        }
        if ($this->_sef) {
            static::getDb()
                ->createCommand()
                ->batchInsert(
                    'sef',
                    ['link', 'link_sef'],
                    [[$this->_sef_start . $this->id, $this->_sef]]
                )
                ->execute();
        }
        return true;
    }

    public function afterDelete()
    {
        parent::afterDelete(); // TODO: Change the autogenerated stub

        static::getDb()
            ->createCommand()
            ->delete('sef', ['link' => $this->_sef_start . $this->id])
            ->execute();
    }
}